rbh_file: "OUTER_SP1_SP2_SP3.rbh" # The order of the species in this name doesn't matter
outgroup: "OUTER"
species1: "SP1"
species2: "SP2"
species3: "SP3"

## This is the decay simulation.
#num_swaps: 5000 # around 7 miniutes
#num_simulations: 5000

# randomization trials. Should be divisible by 100,000
num_randomizations:  100000000

species:
  # bilats
  OUTER: # three-letter code version
    genome:      "/path/to/OUTER.fasta"
    chrom: "/path/to/OUTER.chrom"
    proteins:    "/path/to/OUTER.pep"
  SP1: # three-letter code version
    genome:      "/path/to/SP1.fasta"
    chrom: "/path/to/SP1.chrom"
    proteins:    "/path/to/SP1.pep"
  SP2: # three-letter code version
    genome:      "/path/to/SP2.fasta"
    chrom: "/path/to/SP2.chrom"
    proteins:    "/path/to/SP2.pep"
  INN: # three-letter code version
    genome:      "/path/to/INN.fasta"
    chrom: "/path/to/INN.chrom"
    proteins:    "/path/to/INN.pep"
