#!/usr/bin/env python
"""
This reads in the edge stats and node stats and plots the phylogenetic tree.
Does an easy algorithm and sorts by the lineage.

The --presence_fusion file should be a TSV file containing per-species ALG (ancestral linkage group) presence and fusion information.
Typical filename: per_species_ALG_presence_fusions.tsv
This file is generated by running plot_ALG_fusions_v3.py or plot_ALG_fusions_v2.py earlier in the pipeline.
"""

import argparse
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import os
import pandas as pd
import sys

# import from other program
from Newick_to_common_ancestors import TaxIDtree
from odp_plotting_functions import format_matplotlib


def parse_args():
    """
    The args that we need are:
      - Node stats file
      - Edge stats file
      - Per_species presence_fusion file - this is used to make a pixel plot

    We just check that these exist. Currently there are no rules that we need to define for plotting.

    Returns:
        args: The parsed arguments
    """
    parser = argparse.ArgumentParser(description='Plot the phylogenetic tree')
    parser.add_argument('-n', '--node_stats', type=str, required=True, help='The node stats file')
    parser.add_argument('-e', '--edge_stats', type=str, required=True, help='The edge stats file')
    parser.add_argument('-p', '--presence_fusion', type=str, required=True,
        help='The presence fusion file (TSV, e.g. per_species_ALG_presence_fusions.tsv, generated by plot_ALG_fusions_v3.py or plot_ALG_fusions_v2.py)')
    args = parser.parse_args()

    if not os.path.exists(args.node_stats):
        sys.exit('Node stats file does not exist: {}'.format(args.node_stats))

    if not os.path.exists(args.edge_stats):
        sys.exit('Edge stats file does not exist: {}'.format(args.edge_stats))

    return args

def main():
    args = parse_args()

    perspchromdf = pd.read_csv(args.presence_fusion, sep='\t')

    edgedf = pd.read_csv(args.edge_stats, sep='\t')
    nodedf = pd.read_csv(args.node_stats, sep='\t')
    
    print(f"\n=== Original columns in edgedf ===")
    print(f"Total columns: {len(edgedf.columns)}")
    print("Columns:", edgedf.columns.tolist())
    print()
    
    # Drop per-clade summary columns (from plot_branch_stats_vs_time.py Phase 1)
    # These aren't needed for branch-level tree visualization
    clade_cols = [col for col in nodedf.columns if 'in_this_clade' in col]
    if clade_cols:
        nodedf = nodedf.drop(columns=clade_cols)
        print(f"Dropped {len(clade_cols)} per-clade summary columns from nodedf")
    
    # Drop columns from edgedf that TaxEdge doesn't recognize
    # Keep only the expected TaxEdge attributes
    expected_edge_cols = ['parent_taxid', 'child_taxid', 'parent_age', 'child_age', 
                          'branch_length', 'dist_crown_plus_this_edge',
                          'parent_lineage', 'child_lineage',
                          'num_fusions_this_branch', 'num_losses_this_branch',
                          'num_fusions_per_my_this_branch', 'num_losses_per_my_this_branch',
                          'num_dispersals_per_my_this_branch',  # Add dispersals
                          'fusions', 'losses']
    extra_edge_cols = [col for col in edgedf.columns if col not in expected_edge_cols]
    if extra_edge_cols:
        edgedf = edgedf.drop(columns=extra_edge_cols)
        print(f"Dropped {len(extra_edge_cols)} extra columns from edgedf")

    #print("fusions: max={}, min={}".format(edgedf["num_fusions_per_my_this_branch"].max(), edgedf["num_fusions_per_my_this_branch"].min()))
    #print("losses: max={}, min={}".format(edgedf["num_losses_per_my_this_branch"].max(), edgedf["num_losses_per_my_this_branch"].min()))

    # Debug: Check what values exist in the columns we're trying to plot
    print("\n=== Debugging edge statistics ===")
    for col in ['num_fusions_per_my_this_branch', 'num_dispersals_per_my_this_branch']:
        if col in edgedf.columns:
            print(f"\n{col}:")
            print(f"  dtype: {edgedf[col].dtype}")
            print(f"  null count: {edgedf[col].isna().sum()}")
            print(f"  zero count: {(edgedf[col] == 0).sum()}")
            print(f"  non-zero, non-null count: {((edgedf[col] != 0) & edgedf[col].notna()).sum()}")
            print(f"  min (excluding 0/null): {edgedf[edgedf[col] > 0][col].min() if len(edgedf[edgedf[col] > 0]) > 0 else 'N/A'}")
            print(f"  max: {edgedf[col].max()}")
            print(f"  sample values: {edgedf[col].head(10).tolist()}")
        else:
            print(f"\n{col}: COLUMN NOT FOUND")
    print("=" * 50 + "\n")

    # make a tree
    tree = TaxIDtree()
    # update the tree with the nodes (pass filtered DataFrames directly)
    tree.ingest_node_edge(nodedf, edgedf)

    # just for QC, print the first 10 nodes of the sorted nodes and their lineages
    for i in range(len(tree.leaf_order)):
        node = tree.leaf_order[i]
        print(node, tree.nodes[node].lineage)
        if i == 5:
            break

    format_matplotlib()
    # make a simple matplotlib figure with one axis onto which we can plot
    # Determine how many panels we need based on available columns
    panels = ['base']  # Always have base tree
    if 'num_fusions_per_my_this_branch' in edgedf.columns:
        panels.append('fusions')
    if 'num_dispersals_per_my_this_branch' in edgedf.columns:
        panels.append('dispersals')
    
    num_panels = len(panels)
    print(f"\nGenerating {num_panels} panels: {panels}\n")
    
    # set the dimensions for 20in per plot
    fig, axes = plt.subplots(num_panels, 1, figsize=(20, 20 * num_panels))
    if num_panels == 1:
        axes = [axes]  # Make it a list for consistent indexing
    
    # Plot base tree
    axes[0] = tree.plot_tree(axes[0], sort = "ascending", text_older_than = 50)
    axes[0].set_ylim(0, 800)
    axes[0].set_title("Phylogenetic Tree")
    
    panel_idx = 1
    # Plot fusions if available
    if 'num_fusions_per_my_this_branch' in edgedf.columns:
        axes[panel_idx] = tree.plot_tree(axes[panel_idx], variable = "num_fusions_per_my_this_branch", sort = "ascending", draw_horizontal_bars = False)
        axes[panel_idx].set_ylim(0, 800)
        axes[panel_idx].set_title("Chromosome Fusions per MY")
        panel_idx += 1
    
    # Plot dispersals if available
    if 'num_dispersals_per_my_this_branch' in edgedf.columns:
        axes[panel_idx] = tree.plot_tree(axes[panel_idx], variable = "num_losses_per_my_this_branch", sort = "ascending", draw_horizontal_bars = False)
        axes[panel_idx].set_ylim(0, 800)
        axes[panel_idx].set_title("Chromosome Dispersals per MY")
        panel_idx += 1
    
    # save as a pdf
    plt.savefig('tree.pdf')
    
    # Create diagnostic PDFs with tree overlaid on colored branches
    # This helps diagnose whether colored lines extend beyond branch boundaries
    if 'num_fusions_per_my_this_branch' in edgedf.columns and 'num_dispersals_per_my_this_branch' in edgedf.columns:
        print("\nCreating diagnostic overlay plots...")
        
        # Diagnostic plot 1: Fusions with tree overlay
        fig1, ax1 = plt.subplots(1, 1, figsize=(20, 20))
        # First plot colored fusion branches
        ax1 = tree.plot_tree(ax1, variable = "num_fusions_per_my_this_branch", sort = "ascending", draw_horizontal_bars = False)
        # Then overlay the base tree structure
        ax1 = tree.plot_tree(ax1, sort = "ascending", draw_horizontal_bars = True)
        ax1.set_ylim(0, 800)
        ax1.set_title("Diagnostic: Fusions (colored) with Tree Overlay (black)")
        plt.savefig('tree_diagnostic_fusions_overlay.pdf')
        plt.close(fig1)
        
        # Diagnostic plot 2: Dispersals with tree overlay
        fig2, ax2 = plt.subplots(1, 1, figsize=(20, 20))
        # First plot colored dispersal branches
        ax2 = tree.plot_tree(ax2, variable = "num_losses_per_my_this_branch", sort = "ascending", draw_horizontal_bars = False)
        # Then overlay the base tree structure
        ax2 = tree.plot_tree(ax2, sort = "ascending", draw_horizontal_bars = True)
        ax2.set_ylim(0, 800)
        ax2.set_title("Diagnostic: Dispersals (colored) with Tree Overlay (black)")
        plt.savefig('tree_diagnostic_dispersals_overlay.pdf')
        plt.close(fig2)
        
        print("Diagnostic PDFs saved: tree_diagnostic_fusions_overlay.pdf and tree_diagnostic_dispersals_overlay.pdf")
    
    # Create 2D bivariate color mapping PDFs
    if 'num_fusions_per_my_this_branch' in edgedf.columns and 'num_dispersals_per_my_this_branch' in edgedf.columns:
        print("\nCreating 2D bivariate color mapping plots...")
        
        # Define library of magenta/purple variants to test
        magenta_variants = {
            'softer_purple': [0.6, 0.3, 0.6],
            'balanced_purple': [0.7, 0.2, 0.7],
            'true_magenta': [0.9, 0.0, 0.9],
            'lavender': [0.8, 0.4, 0.8],
            'violet': [0.5, 0.0, 0.7]
        }
        
        for variant_name, magenta_color in magenta_variants.items():
            print(f"  Generating variant: {variant_name}")
            
            # Temporarily set the magenta color in tree (if we add a parameter)
            # For now, the color is hardcoded in plot_tree, so all variants will use same color
            # We'll generate one set for now
            
            # Main 2D bivariate plot: 4 panels with legend
            from matplotlib.gridspec import GridSpec
            fig3 = plt.figure(figsize=(20, 80))
            gs = GridSpec(4, 1, height_ratios=[20, 5, 20, 20], hspace=0.3, figure=fig3)
            
            ax0 = fig3.add_subplot(gs[0])
            ax1 = fig3.add_subplot(gs[1])
            ax2 = fig3.add_subplot(gs[2])
            ax3 = fig3.add_subplot(gs[3])
            
            # Panel 1: Base tree structure
            ax0 = tree.plot_tree(ax0, sort="ascending", draw_horizontal_bars=True)
            ax0.set_ylim(0, 800)
            ax0.set_title("Phylogenetic Tree Structure", fontsize=16)
            
            # Panel 3: 2D colored tree (colors only, no structure)
            # TUNING PARAMETERS:
            #   split_buffer_pct: whitespace between tips (0.0=no gap, 0.2=20% gap)
            #   split_width_scale: width increase from tips to root (1.0=constant, 2.0=3x wider at root)
            #   bar_width_base: tip width multiplier (1.0=use split_buffer_pct width, 1.25=eliminate gaps when split_buffer_pct=0.2)
            ax2 = tree.plot_tree(ax2, 
                                variable=("num_losses_per_my_this_branch", "num_fusions_per_my_this_branch"),
                                sort="ascending", 
                                draw_horizontal_bars=False,
                                split_buffer_pct=0.0,
                                split_width_scale=30,
                                bar_width_base=1.5,
                                magenta_color=magenta_color)
            ax2.set_ylim(0, 800)
            ax2.set_title(f"2D Bivariate ({variant_name}): Colors Only", fontsize=16)
            
            # Panel 4: 2D colored tree with structure (colors + horizontal bars + zero branches)
            # TUNING PARAMETERS:
            #   split_buffer_pct: whitespace between tips (0.0=no gap, 0.2=20% gap)
            #   split_width_scale: width increase from tips to root (1.0=constant, 2.0=3x wider at root)
            #   bar_width_base: tip width multiplier (1.0=use split_buffer_pct width, 1.25=eliminate gaps when split_buffer_pct=0.2)
            ax3 = tree.plot_tree(ax3, 
                                variable=("num_losses_per_my_this_branch", "num_fusions_per_my_this_branch"),
                                sort="ascending", 
                                draw_horizontal_bars=True,
                                split_buffer_pct=0.0,
                                split_width_scale=30,
                                bar_width_base=1.5,
                                magenta_color=magenta_color)
            ax3.set_ylim(0, 800)
            ax3.set_title(f"2D Bivariate ({variant_name}): Colors + Structure", fontsize=16)
            
            # Panel 2: 2D color legend (smaller) with actual values
            if hasattr(tree, '_2d_color_params') and tree._2d_color_params is not None:
                minv1, maxv1, minv2, maxv2 = tree._2d_color_params
                ax1 = tree.create_2d_colorbar_legend(ax1, 
                                                     var1_name="Dispersals", 
                                                     var2_name="Fusions",
                                                     var1_range=(minv1, maxv1),
                                                     var2_range=(minv2, maxv2),
                                                     magenta_color=magenta_color)
            else:
                ax1 = tree.create_2d_colorbar_legend(ax1, var1_name="Dispersals", var2_name="Fusions", magenta_color=magenta_color)
            
            plt.savefig(f'tree_2d_bivariate_{variant_name}.pdf')
            plt.close(fig3)
        
        print(f"2D bivariate PDFs saved for all variants.")
        
        # Create split-side visualization with two panels and legends
        print("\nCreating split-side visualization (dispersals left, fusions right)...")
        from matplotlib.gridspec import GridSpec
        fig_split = plt.figure(figsize=(40, 25))
        gs_split = GridSpec(2, 2, width_ratios=[20, 20], height_ratios=[20, 2], hspace=0.2, wspace=0.1, figure=fig_split)
        
        ax_split1 = fig_split.add_subplot(gs_split[0, 0])
        ax_split2 = fig_split.add_subplot(gs_split[0, 1])
        ax_legend_dispersals = fig_split.add_subplot(gs_split[1, 0])
        ax_legend_fusions = fig_split.add_subplot(gs_split[1, 1])
        
        # Panel 1: Just colored splits, no horizontal bars, skip zero branches
        ax_split1 = tree.plot_tree(ax_split1, 
                                   variable=("num_losses_per_my_this_branch", "num_fusions_per_my_this_branch"),
                                   sort="ascending", 
                                   draw_horizontal_bars=False,
                                   split_side_mode=True,
                                   split_draw_zero_branches=False,
                                   randomize_order=True,
                                   split_buffer_pct=0.0,
                                   split_width_scale=60.0,
                                   bar_width_base=1.5)
        ax_split1.set_ylim(0, 800)
        ax_split1.set_title("Panel 1: Colored Splits Only (No Zero Values)", fontsize=16)
        
        # Panel 2: Colored splits + horizontal bars + zero branches
        ax_split2 = tree.plot_tree(ax_split2, 
                                   variable=("num_losses_per_my_this_branch", "num_fusions_per_my_this_branch"),
                                   sort="ascending", 
                                   draw_horizontal_bars=True,
                                   split_side_mode=True,
                                   split_draw_zero_branches=True,
                                   randomize_order=True,
                                   split_buffer_pct=0.0,
                                   split_width_scale=60.0,
                                   bar_width_base=1.5)
        ax_split2.set_ylim(0, 800)
        ax_split2.set_title("Panel 2: Splits + Structure (With Zero Branches)", fontsize=16)
        
        # Create dispersals legend (red gradient)
        if hasattr(tree, '_2d_color_params') and tree._2d_color_params is not None:
            minv1, maxv1, minv2, maxv2 = tree._2d_color_params
            
            # Dispersals legend
            gradient = np.linspace(0, 1, 256).reshape(1, -1)
            red_cmap = mcolors.LinearSegmentedColormap.from_list("", ["white", "#D22C16"])
            ax_legend_dispersals.imshow(gradient, aspect='auto', cmap=red_cmap)
            ax_legend_dispersals.set_xlabel('Dispersals (per MY)', fontsize=12)
            ax_legend_dispersals.set_yticks([])
            # Set log-spaced ticks
            x_ticks_log = np.linspace(0, 255, 5)
            x_ticks_values = np.logspace(np.log10(minv1), np.log10(maxv1), 5)
            ax_legend_dispersals.set_xticks(x_ticks_log)
            ax_legend_dispersals.set_xticklabels([f'{v:.3f}' if v < 1 else f'{v:.1f}' for v in x_ticks_values])
            
            # Fusions legend
            blue_cmap = mcolors.LinearSegmentedColormap.from_list("", ["white", "#3054A3"])
            ax_legend_fusions.imshow(gradient, aspect='auto', cmap=blue_cmap)
            ax_legend_fusions.set_xlabel('Fusions (per MY)', fontsize=12)
            ax_legend_fusions.set_yticks([])
            # Set log-spaced ticks
            x_ticks_values_fusions = np.logspace(np.log10(minv2), np.log10(maxv2), 5)
            ax_legend_fusions.set_xticks(x_ticks_log)
            ax_legend_fusions.set_xticklabels([f'{v:.3f}' if v < 1 else f'{v:.1f}' for v in x_ticks_values_fusions])
        
        plt.savefig('tree_split_side.pdf')
        plt.close(fig_split)
        print("Split-side PDF saved: tree_split_side.pdf")

    # get the leaf order of the tree
    node_order = tree.leaf_order
    from plot_ALG_fusions_v3 import standard_plot_out
    standard_plot_out(perspchromdf, "matches_tree", taxid_order = node_order)

if __name__ == '__main__':
    main()